### PR TITLE
updated docs

### LINKED ISSUE #62: Outdated documentation (example section)
## Current behaviour
The documentation section `example` does not show the new release example.

## Expected behaviour
The documentation section `example` is up to date accordingly latest release, and follow default behavior.

## Checklist (after created issue)
- [x] Added label(s)
- [x] Added to project
- [x] Added to milestone

### LINKED ISSUE #83: Documentation formatting & missing info
### 1 Formatting
Screenshot 2020-11-09 at 08 05 43

### 2 Missing creds
In section [Example](https://github.com/fredrikhgrelland/terraform-nomad-minio#example), 
`vault_secret.use_vault_provider` set it to false, but use creds do not provided, such as `access_key ` and `secret_key`

Some of the content put in-line
## Checklist (after created issue)
- [x] Added label(s)
- [x] Added to project
- [x] Added to milestone

### PR DESCRIPTION
**Pull request by dangernil**
## Closes/fixes/resolves issue(s)?
Closes #83 

## What was added/changed/fixed?
Updated docs

## Checklist (after created PR)
- [x] Added reviewers
- [x] Added assignee(s)
- [x] Added label(s)
- [x] Added to project
- [x] Added to milestone

### CODE REVIEW

**Comment by claesgill** [comment]
Need to update the example section to be able to close #62

**Comment by zhenik** [comment]
> Need to update the example section to be able to close #62

I think #62 was fixed by https://github.com/fredrikhgrelland/terraform-nomad-minio/pull/84

**Comment by claesgill** [comment]
> > Need to update the example section to be able to close #62
> 
> I think #62 was fixed by #84

Shouldn't we provide the default settings as well? E.g. `use_vault_prover = false` in that example.

**Comment by zhenik** [comment]
> > > Need to update the example section to be able to close #62
> > 
> > 
> > I think #62 was fixed by #84
> 
> Shouldn't we provide the default settings as well? E.g. `use_vault_prover = false` in that example.

I say yes. I think it's good for documentation.

**Comment by claesgill** [comment]
> > > > Need to update the example section to be able to close #62
> > > 
> > > 
> > > I think #62 was fixed by #84
> > 
> > 
> > Shouldn't we provide the default settings as well? E.g. `use_vault_prover = false` in that example.
> 
> I say yes. I think it's good for documentation.

Agree. Reopening #62

**Review by claesgill — APPROVED** [review]
LGTM

**Review by pdmthorsrud — APPROVED** [review]

**Pull request merged**
