### PR TITLE
added skip-duplicate-runs action

### LINKED ISSUE #62: Outdated documentation (example section)
## Current behaviour
The documentation section `example` does not show the new release example.

## Expected behaviour
The documentation section `example` is up to date accordingly latest release, and follow default behavior.

## Checklist (after created issue)
- [x] Added label(s)
- [x] Added to project
- [x] Added to milestone

### LINKED ISSUE #78: Update workflow to handle duplicate runs
## Feature description
Update workflow to handle duplicate runs so we don't have to manually cancel runs.

## Why is it needed?
To reduce time to execute pipeline runs as duplicate runs occur.

## Checklist (after created issue)
- [x] Added label(s)
- [x] Added to project
- [x] Added to milestone

### PR DESCRIPTION
**Pull request by dangernil**
## Closes/fixes/resolves issue(s)?
Closes #78 
Closes #62  

## What was added/changed/fixed?
- Added skip-duplicate-runs

## Others [Optional]
https://github.com/marketplace/actions/skip-duplicate-actions

## Checklist (after created PR)
- [x] Added reviewers
- [x] Added assignee(s)
- [x] Added label(s)
- [x] Added to project
- [x] Added to milestone

### CODE REVIEW

**Comment by zhenik** [comment]
I am unsure that it works (check tab actions). To trigger new run, I have just edit PR description (added line shift)
Screenshot 2020-11-13 at 12 12 48

**Comment by dangernil** [comment]
Edits in the PR does start a new workflow run, and the skip-job does not cancel the runs even though they are duplicates. But if there is a push to the branch it will backtrack and cancel all active runs. So I don't think this is a issue as whenever a proper push goes to the branch it do actually cancel runs.

**Review by zhenik — APPROVED** [review]

**Review by claesgill — APPROVED** [review]

**Comment by claesgill** [comment]
Can you fix this in the `vagrant-hashistack-template` as well? 

Also, if we decide to not sync with the template, we possibly need to do this in all the modules as well. WDYT? @zhenik @pdmthorsrud @dangernil

**Comment by zhenik** [comment]
> Can you fix this in the `vagrant-hashistack-template` as well?
> 
> Also, if we decide to not sync with the template, we possibly need to do this in all the modules as well. WDYT? @zhenik @pdmthorsrud @dangernil

I would look for an opportunity trigger cancel duplicate run for all GitHub actions (labeled, unlabeled, edit, etc...), no only for commit-push, than it would be nice to upstream

**Comment by claesgill** [comment]
> > Can you fix this in the `vagrant-hashistack-template` as well?
> > Also, if we decide to not sync with the template, we possibly need to do this in all the modules as well. WDYT? @zhenik @pdmthorsrud @dangernil
> 
> I would look for an opportunity trigger cancel duplicate run for all GitHub actions (labeled, unlabeled, edit, etc...), no only for commit-push, than it would be nice to upstream

Good point. Let's wait for that. I also hope we can prioritize that task :)

**Review by pdmthorsrud — APPROVED** [review]

**Comment by dangernil** [comment]
So do we want to add this for now and look for a better one at a later point? I feel it's better to have this while we wait for a more suitable approach, better than nothing so to speak.

**Pull request merged**
