### PR TITLE
fixed release-prerequisites

### PR DESCRIPTION
**Pull request by pdmthorsrud**
## Checklist (after created PR)
- [ ] Added reviewers
- [ ] Added assignee(s)
- [ ] Added label(s)
- [ ] Added to project
- [ ] Added to milestone

### CODE REVIEW

**Comment by pdmthorsrud** [comment]
Thinking about it, this might actually be more suitable to include when we have our next release, just so that it can be tested at the same time. WDYT?

**Review by dangernil — APPROVED** [review]

**Comment by claesgill** [comment]
> Thinking about it, this might actually be more suitable to include when we have our next release, just so that it can be tested at the same time. WDYT?

See respond 👉 https://github.com/fredrikhgrelland/terraform-nomad-postgres/pull/61#issuecomment-733519565

**Comment by pdmthorsrud** [comment]
> > Thinking about it, this might actually be more suitable to include when we have our next release, just so that it can be tested at the same time. WDYT?
> 
> See respond 👉 [fredrikhgrelland/terraform-nomad-postgres#61 (comment)](https://github.com/fredrikhgrelland/terraform-nomad-postgres/pull/61#issuecomment-733519565)

See answer 👉 https://github.com/fredrikhgrelland/terraform-nomad-postgres/pull/61#issuecomment-733524853

**Comment by claesgill** [comment]
> > > Thinking about it, this might actually be more suitable to include when we have our next release, just so that it can be tested at the same time. WDYT?
> > 
> > 
> > See respond 👉 [fredrikhgrelland/terraform-nomad-postgres#61 (comment)](https://github.com/fredrikhgrelland/terraform-nomad-postgres/pull/61#issuecomment-733519565)
> 
> See answer 👉 [fredrikhgrelland/terraform-nomad-postgres#61 (comment)](https://github.com/fredrikhgrelland/terraform-nomad-postgres/pull/61#issuecomment-733524853)

See reaction 👉 https://github.com/fredrikhgrelland/terraform-nomad-postgres/pull/61#issuecomment-733524853

**Comment by pdmthorsrud** [comment]
@claesgill @zhenik 
this has now run successfully in hive, so I think we are good to merge this now
https://github.com/fredrikhgrelland/terraform-nomad-hive/actions/runs/382715027

**Review by zhenik — APPROVED** [review]
GJ

**Pull request merged**
